### ISSUE TITLE
Some question about paper

### ISSUE THREAD

**Issue by DuinoDu** [slryou41/AnchorLoss#1]
Hi, thanks for your awesome work!
I have one question when reading paper. In human pose estimation training, it said 

> Note that we put sigmoid activation layer on top of the standard architecture to perform classifacation.

The question is, how you process learning label? do you use gaussian heatmap or circle plate as used in [grmi](https://arxiv.org/pdf/1701.01779.pdf)?

Much thanks!

**Comment by slryou41** [comment]
Thanks for your interest! We follow the hourglass paper to generate gaussian heatmap (not the circle plate) and add sigmoid layer on top of the output predictions.
